spring.application.name=TaskManager 
spring.datasource.url=jdbc:postgresql://dpg-d1apsvqdbo4c73884r80-a:5432/task_db_p1k8
spring.datasource.username=task_db_p1k8_user
spring.datasource.password=82qX9sjO1ZaxKie5Kg2J9EMvkOKpd3J5
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
